import React from 'react';
export declare const TableIcon: () => React.JSX.Element;
export declare const GridIcon: () => React.JSX.Element;
export declare const BoardIcon: () => React.JSX.Element;
export declare const ListIcon: () => React.JSX.Element;
export declare const TimelineIcon: () => React.JSX.Element;
export declare const CalendarIcon: () => React.JSX.Element;
export declare const ReportIcon: () => React.JSX.Element;
export declare const FeedIcon: () => React.JSX.Element;
export declare const AppletIcon: () => React.JSX.Element;
export declare const OverviewIcon: () => React.JSX.Element;
export declare const MeetingsIcon: () => React.JSX.Element;
export declare const TaskIcon: () => React.JSX.Element;
export declare const FilesIcon: () => React.JSX.Element;
export declare const SettingsIcon: () => React.JSX.Element;
export declare const MembersIcon: () => React.JSX.Element;
export declare const TabsIcon: () => React.JSX.Element;
export declare const StatusesIcon: () => React.JSX.Element;
