import React from "react";
export declare namespace FieldIcons {
    const RightArrow: () => React.JSX.Element;
    const Plus: () => React.JSX.Element;
    const TextAttribute: () => React.JSX.Element;
    const RichTextAttribute: () => React.JSX.Element;
    const NumberAttribute: () => React.JSX.Element;
    const SingleSelectAttribute: () => React.JSX.Element;
    const MultiSelectAttribute: () => React.JSX.Element;
    const WorkflowAttribute: () => React.JSX.Element;
    const AssignmentAttribute: () => React.JSX.Element;
    const DateAttribute: () => React.JSX.Element;
    const CheckboxAttribute: () => React.JSX.Element;
    const URLAttribute: () => React.JSX.Element;
    const EmailAttribute: () => React.JSX.Element;
    const PhoneAttribute: () => React.JSX.Element;
    const LocationAttribute: () => React.JSX.Element;
    const AvatarAttribute: () => React.JSX.Element;
    const IconAttribute: () => React.JSX.Element;
    const FilesAttribute: () => React.JSX.Element;
    const CommentsAttribute: () => React.JSX.Element;
    const RelationToAttribute: () => React.JSX.Element;
    const LookupFromAttribute: () => React.JSX.Element;
    const FormulaAttribute: () => React.JSX.Element;
    const DocumentAttribute: () => React.JSX.Element;
    const RelationAttribute: () => React.JSX.Element;
    const Collection: () => React.JSX.Element;
    const Relation: () => React.JSX.Element;
}
