import React from "react";
export declare namespace WorkbenchIcons {
    const NotebookIcon: (props: any) => React.JSX.Element;
    const FormIcon: (props: any) => React.JSX.Element;
    const CollapseRightIcon: (props: any) => React.JSX.Element;
    const CollapseLeftIcon: (props: any) => React.JSX.Element;
    const DocIcon: (props: any) => React.JSX.Element;
    const DocIcon2: (props: any) => React.JSX.Element;
    const WhiteboardIcon: (props: any) => React.JSX.Element;
    const AddFolder: (props: any) => React.JSX.Element;
    const FolderClosed: (props: any) => React.JSX.Element;
    const Edit: (props: any) => React.JSX.Element;
    const Link: (props: any) => React.JSX.Element;
    const Copy: (props: any) => React.JSX.Element;
    const CaretDown: (props: any) => React.JSX.Element;
    const CaretRight: (props: any) => React.JSX.Element;
    const Gantt: (props: any) => React.JSX.Element;
    const KanbanBoard: (props: any) => React.JSX.Element;
    const ObjectiveIcon: (props: any) => React.JSX.Element;
    const DashboardIcon: (props: any) => React.JSX.Element;
    const BPMNIcon: (props: any) => React.JSX.Element;
    const SpreadsheetIcon: (props: any) => React.JSX.Element;
    const Download: (props: any) => React.JSX.Element;
    const Import: (props: any) => React.JSX.Element;
    const TableIcon: () => React.JSX.Element;
    const GridIcon: () => React.JSX.Element;
    const BoardIcon: () => React.JSX.Element;
    const ListIcon: () => React.JSX.Element;
    const TimelineIcon: () => React.JSX.Element;
    const CalendarIcon: () => React.JSX.Element;
    const ReportIcon: () => React.JSX.Element;
    const FeedIcon: () => React.JSX.Element;
    const MapIcon: () => React.JSX.Element;
    const DocumentIcon: () => React.JSX.Element;
    const WhiteboardIcon1: () => React.JSX.Element;
    const FormIcon1: () => React.JSX.Element;
}
